//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarhangSarah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarhangSarahDBEntities : DbContext
    {
        public FarhangSarahDBEntities()
            : base("name=FarhangSarahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Enroll> Enroll { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
